// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Ad formats handled natively.
enum AdFormatMessage { banner, interstitial, rewarded, appOpen }

/// Event kinds sent from native to Dart.
enum AdEventKind {
  loaded,
  failedToLoad,
  failedToShow,
  shown,
  impression,
  clicked,
  closed,
  earnedReward,
  bannerSized,
}

class InitRequest {
  InitRequest({
    required this.appId,
    required this.testMode,
    required this.testDeviceIds,
    this.userId,
  });

  /// The network's app-level credential (see the adapter's setup doc).
  String appId;

  bool testMode;

  List<String> testDeviceIds;

  String? userId;

  List<Object?> _toList() {
    return <Object?>[appId, testMode, testDeviceIds, userId];
  }

  Object encode() {
    return _toList();
  }

  static InitRequest decode(Object result) {
    result as List<Object?>;
    return InitRequest(
      appId: result[0]! as String,
      testMode: result[1]! as bool,
      testDeviceIds: (result[2]! as List<Object?>).cast<String>(),
      userId: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InitRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(appId, other.appId) &&
        _deepEquals(testMode, other.testMode) &&
        _deepEquals(testDeviceIds, other.testDeviceIds) &&
        _deepEquals(userId, other.userId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'InitRequest(appId: $appId, testMode: $testMode, testDeviceIds: $testDeviceIds, userId: $userId)';
  }
}

/// Native facts reported back after initialization.
class InitInfo {
  InitInfo({this.metaBiddingAdapter});

  /// Class name of the Meta (Facebook) bidding adapter the app added to its
  /// build, or null when none is present (see docs/setup).
  String? metaBiddingAdapter;

  List<Object?> _toList() {
    return <Object?>[metaBiddingAdapter];
  }

  Object encode() {
    return _toList();
  }

  static InitInfo decode(Object result) {
    result as List<Object?>;
    return InitInfo(metaBiddingAdapter: result[0] as String?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InitInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(metaBiddingAdapter, other.metaBiddingAdapter);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'InitInfo(metaBiddingAdapter: $metaBiddingAdapter)';
  }
}

class ConsentMessage {
  ConsentMessage({
    this.gdprApplies,
    this.consentGiven,
    this.ccpaOptOut,
    required this.coppa,
  });

  bool? gdprApplies;

  bool? consentGiven;

  bool? ccpaOptOut;

  bool coppa;

  List<Object?> _toList() {
    return <Object?>[gdprApplies, consentGiven, ccpaOptOut, coppa];
  }

  Object encode() {
    return _toList();
  }

  static ConsentMessage decode(Object result) {
    result as List<Object?>;
    return ConsentMessage(
      gdprApplies: result[0] as bool?,
      consentGiven: result[1] as bool?,
      ccpaOptOut: result[2] as bool?,
      coppa: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConsentMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(gdprApplies, other.gdprApplies) &&
        _deepEquals(consentGiven, other.consentGiven) &&
        _deepEquals(ccpaOptOut, other.ccpaOptOut) &&
        _deepEquals(coppa, other.coppa);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConsentMessage(gdprApplies: $gdprApplies, consentGiven: $consentGiven, ccpaOptOut: $ccpaOptOut, coppa: $coppa)';
  }
}

class AdEventMessage {
  AdEventMessage({
    required this.kind,
    required this.adId,
    required this.format,
    this.errorCode,
    this.errorMessage,
    this.nativeCode,
    this.rewardAmount,
    this.rewardType,
    this.width,
    this.height,
  });

  AdEventKind kind;

  String adId;

  AdFormatMessage format;

  /// An AdErrorCode name, for failure events.
  String? errorCode;

  String? errorMessage;

  String? nativeCode;

  double? rewardAmount;

  String? rewardType;

  double? width;

  double? height;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      adId,
      format,
      errorCode,
      errorMessage,
      nativeCode,
      rewardAmount,
      rewardType,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AdEventMessage decode(Object result) {
    result as List<Object?>;
    return AdEventMessage(
      kind: result[0]! as AdEventKind,
      adId: result[1]! as String,
      format: result[2]! as AdFormatMessage,
      errorCode: result[3] as String?,
      errorMessage: result[4] as String?,
      nativeCode: result[5] as String?,
      rewardAmount: result[6] as double?,
      rewardType: result[7] as String?,
      width: result[8] as double?,
      height: result[9] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AdEventMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(adId, other.adId) &&
        _deepEquals(format, other.format) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(errorMessage, other.errorMessage) &&
        _deepEquals(nativeCode, other.nativeCode) &&
        _deepEquals(rewardAmount, other.rewardAmount) &&
        _deepEquals(rewardType, other.rewardType) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AdEventMessage(kind: $kind, adId: $adId, format: $format, errorCode: $errorCode, errorMessage: $errorMessage, nativeCode: $nativeCode, rewardAmount: $rewardAmount, rewardType: $rewardType, width: $width, height: $height)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is AdFormatMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is AdEventKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is InitRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is InitInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is ConsentMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is AdEventMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AdFormatMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AdEventKind.values[value];
      case 131:
        return InitRequest.decode(readValue(buffer)!);
      case 132:
        return InitInfo.decode(readValue(buffer)!);
      case 133:
        return ConsentMessage.decode(readValue(buffer)!);
      case 134:
        return AdEventMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart to native. Failures are platform errors whose code is an AdErrorCode
/// name and whose details is the SDK error code.
class ApplovinHostApi {
  /// Constructor for [ApplovinHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ApplovinHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<InitInfo> initialize(InitRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unified_ads_applovin.ApplovinHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as InitInfo;
  }

  /// Loads a full-screen ad and returns its id.
  Future<String> load(AdFormatMessage format, String adUnitId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unified_ads_applovin.ApplovinHostApi.load$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[format, adUnitId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  /// Completes when the ad is presented (or failed to present).
  Future<void> show(String adId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unified_ads_applovin.ApplovinHostApi.show$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[adId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> destroy(String adId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unified_ads_applovin.ApplovinHostApi.destroy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[adId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> applyConsent(ConsentMessage consent) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unified_ads_applovin.ApplovinHostApi.applyConsent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[consent],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> dispose() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.unified_ads_applovin.ApplovinHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Native to Dart.
abstract class ApplovinEventsApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAdEvent(AdEventMessage event);

  static void setUp(
    ApplovinEventsApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.unified_ads_applovin.ApplovinEventsApi.onAdEvent$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AdEventMessage arg_event = args[0]! as AdEventMessage;
          try {
            api.onAdEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
