// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.arovyx.plugin.unifiedads.startapp

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Ad formats handled natively. */
enum class AdFormatMessage(val raw: Int) {
  BANNER(0),
  INTERSTITIAL(1),
  REWARDED(2);

  companion object {
    fun ofRaw(raw: Int): AdFormatMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Event kinds sent from native to Dart. */
enum class AdEventKind(val raw: Int) {
  LOADED(0),
  FAILED_TO_LOAD(1),
  FAILED_TO_SHOW(2),
  SHOWN(3),
  IMPRESSION(4),
  CLICKED(5),
  CLOSED(6),
  EARNED_REWARD(7),
  BANNER_SIZED(8);

  companion object {
    fun ofRaw(raw: Int): AdEventKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InitRequest (
  /** The network's app-level credential (see the adapter's setup doc). */
  val appId: String,
  val testMode: Boolean,
  val testDeviceIds: List<String>,
  val userId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitRequest {
      val appId = pigeonVar_list[0] as String
      val testMode = pigeonVar_list[1] as Boolean
      val testDeviceIds = pigeonVar_list[2] as List<String>
      val userId = pigeonVar_list[3] as String?
      return InitRequest(appId, testMode, testDeviceIds, userId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      appId,
      testMode,
      testDeviceIds,
      userId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InitRequest
    return MessagesPigeonUtils.deepEquals(this.appId, other.appId) && MessagesPigeonUtils.deepEquals(this.testMode, other.testMode) && MessagesPigeonUtils.deepEquals(this.testDeviceIds, other.testDeviceIds) && MessagesPigeonUtils.deepEquals(this.userId, other.userId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.testMode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.testDeviceIds)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userId)
    return result
  }
  override fun toString(): String {
    return "InitRequest(appId=$appId, testMode=$testMode, testDeviceIds=$testDeviceIds, userId=$userId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConsentMessage (
  val gdprApplies: Boolean? = null,
  val consentGiven: Boolean? = null,
  val ccpaOptOut: Boolean? = null,
  val coppa: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConsentMessage {
      val gdprApplies = pigeonVar_list[0] as Boolean?
      val consentGiven = pigeonVar_list[1] as Boolean?
      val ccpaOptOut = pigeonVar_list[2] as Boolean?
      val coppa = pigeonVar_list[3] as Boolean
      return ConsentMessage(gdprApplies, consentGiven, ccpaOptOut, coppa)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      gdprApplies,
      consentGiven,
      ccpaOptOut,
      coppa,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConsentMessage
    return MessagesPigeonUtils.deepEquals(this.gdprApplies, other.gdprApplies) && MessagesPigeonUtils.deepEquals(this.consentGiven, other.consentGiven) && MessagesPigeonUtils.deepEquals(this.ccpaOptOut, other.ccpaOptOut) && MessagesPigeonUtils.deepEquals(this.coppa, other.coppa)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gdprApplies)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.consentGiven)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ccpaOptOut)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.coppa)
    return result
  }
  override fun toString(): String {
    return "ConsentMessage(gdprApplies=$gdprApplies, consentGiven=$consentGiven, ccpaOptOut=$ccpaOptOut, coppa=$coppa)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AdEventMessage (
  val kind: AdEventKind,
  val adId: String,
  val format: AdFormatMessage,
  /** An AdErrorCode name, for failure events. */
  val errorCode: String? = null,
  val errorMessage: String? = null,
  val nativeCode: String? = null,
  val rewardAmount: Double? = null,
  val rewardType: String? = null,
  val width: Double? = null,
  val height: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AdEventMessage {
      val kind = pigeonVar_list[0] as AdEventKind
      val adId = pigeonVar_list[1] as String
      val format = pigeonVar_list[2] as AdFormatMessage
      val errorCode = pigeonVar_list[3] as String?
      val errorMessage = pigeonVar_list[4] as String?
      val nativeCode = pigeonVar_list[5] as String?
      val rewardAmount = pigeonVar_list[6] as Double?
      val rewardType = pigeonVar_list[7] as String?
      val width = pigeonVar_list[8] as Double?
      val height = pigeonVar_list[9] as Double?
      return AdEventMessage(kind, adId, format, errorCode, errorMessage, nativeCode, rewardAmount, rewardType, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      adId,
      format,
      errorCode,
      errorMessage,
      nativeCode,
      rewardAmount,
      rewardType,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AdEventMessage
    return MessagesPigeonUtils.deepEquals(this.kind, other.kind) && MessagesPigeonUtils.deepEquals(this.adId, other.adId) && MessagesPigeonUtils.deepEquals(this.format, other.format) && MessagesPigeonUtils.deepEquals(this.errorCode, other.errorCode) && MessagesPigeonUtils.deepEquals(this.errorMessage, other.errorMessage) && MessagesPigeonUtils.deepEquals(this.nativeCode, other.nativeCode) && MessagesPigeonUtils.deepEquals(this.rewardAmount, other.rewardAmount) && MessagesPigeonUtils.deepEquals(this.rewardType, other.rewardType) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.adId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.format)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorMessage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nativeCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rewardAmount)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rewardType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "AdEventMessage(kind=$kind, adId=$adId, format=$format, errorCode=$errorCode, errorMessage=$errorMessage, nativeCode=$nativeCode, rewardAmount=$rewardAmount, rewardType=$rewardType, width=$width, height=$height)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AdFormatMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AdEventKind.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConsentMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AdEventMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AdFormatMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AdEventKind -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is InitRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ConsentMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is AdEventMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart to native. Failures are platform errors whose code is an AdErrorCode
 * name and whose details is the SDK error code.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface StartappHostApi {
  suspend fun initialize(request: InitRequest)
  /** Loads a full-screen ad and returns its id. */
  suspend fun load(format: AdFormatMessage, adUnitId: String): String
  /** Completes when the ad is presented (or failed to present). */
  suspend fun show(adId: String)
  fun destroy(adId: String)
  fun applyConsent(consent: ConsentMessage)
  fun dispose()

  companion object {
    /** The codec used by StartappHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `StartappHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: StartappHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unified_ads_startapp.StartappHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as InitRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.initialize(requestArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unified_ads_startapp.StartappHostApi.load$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val formatArg = args[0] as AdFormatMessage
            val adUnitIdArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.load(formatArg, adUnitIdArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unified_ads_startapp.StartappHostApi.show$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.show(adIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unified_ads_startapp.StartappHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unified_ads_startapp.StartappHostApi.applyConsent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val consentArg = args[0] as ConsentMessage
            val wrapped: List<Any?> = try {
              api.applyConsent(consentArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.unified_ads_startapp.StartappHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native to Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class StartappEventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by StartappEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  suspend fun onAdEvent(eventArg: AdEventMessage)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.unified_ads_startapp.StartappEventsApi.onAdEvent$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
