// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Ad formats handled natively.
enum AdFormatMessage: Int, CaseIterable {
  case banner = 0
  case interstitial = 1
  case rewarded = 2
  case rewardedInterstitial = 3
  case appOpen = 4
}

/// Event kinds sent from native to Dart.
enum AdEventKind: Int, CaseIterable {
  case loaded = 0
  case failedToLoad = 1
  case failedToShow = 2
  case shown = 3
  case impression = 4
  case clicked = 5
  case closed = 6
  case earnedReward = 7
  case bannerSized = 8
}

/// Debug geography for the UMP consent flow (testing only).
enum DebugGeographyMessage: Int, CaseIterable {
  case eea = 0
  case regulatedUsState = 1
  case other = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct InitRequest: Hashable, CustomStringConvertible {
  /// App ID from the Dart config, compared against the manifest / Info.plist.
  var appId: String? = nil
  var testMode: Bool
  var testDeviceIds: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitRequest? {
    let appId: String? = nilOrValue(pigeonVar_list[0])
    let testMode = pigeonVar_list[1] as! Bool
    let testDeviceIds = pigeonVar_list[2] as! [String]

    return InitRequest(
      appId: appId,
      testMode: testMode,
      testDeviceIds: testDeviceIds
    )
  }
  func toList() -> [Any?] {
    return [
      appId,
      testMode,
      testDeviceIds,
    ]
  }
  static func == (lhs: InitRequest, rhs: InitRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.appId, rhs.appId) && MessagesPigeonInternal.deepEquals(lhs.testMode, rhs.testMode) && MessagesPigeonInternal.deepEquals(lhs.testDeviceIds, rhs.testDeviceIds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("InitRequest")
    MessagesPigeonInternal.deepHash(value: appId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: testMode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: testDeviceIds, hasher: &hasher)
  }

  public var description: String {
    return "InitRequest(appId: \(String(describing: appId)), testMode: \(String(describing: testMode)), testDeviceIds: \(String(describing: testDeviceIds)))"
  }
}

/// Native facts reported back after initialization.
///
/// Generated class from Pigeon that represents data sent in messages.
struct InitInfo: Hashable, CustomStringConvertible {
  /// Class name of the Meta (Facebook) bidding adapter the app added to its
  /// build, or null when none is present (see docs/setup).
  var metaBiddingAdapter: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitInfo? {
    let metaBiddingAdapter: String? = nilOrValue(pigeonVar_list[0])

    return InitInfo(
      metaBiddingAdapter: metaBiddingAdapter
    )
  }
  func toList() -> [Any?] {
    return [
      metaBiddingAdapter
    ]
  }
  static func == (lhs: InitInfo, rhs: InitInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.metaBiddingAdapter, rhs.metaBiddingAdapter)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("InitInfo")
    MessagesPigeonInternal.deepHash(value: metaBiddingAdapter, hasher: &hasher)
  }

  public var description: String {
    return "InitInfo(metaBiddingAdapter: \(String(describing: metaBiddingAdapter)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConsentMessage: Hashable, CustomStringConvertible {
  var gdprApplies: Bool? = nil
  var consentGiven: Bool? = nil
  var ccpaOptOut: Bool? = nil
  var coppa: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConsentMessage? {
    let gdprApplies: Bool? = nilOrValue(pigeonVar_list[0])
    let consentGiven: Bool? = nilOrValue(pigeonVar_list[1])
    let ccpaOptOut: Bool? = nilOrValue(pigeonVar_list[2])
    let coppa = pigeonVar_list[3] as! Bool

    return ConsentMessage(
      gdprApplies: gdprApplies,
      consentGiven: consentGiven,
      ccpaOptOut: ccpaOptOut,
      coppa: coppa
    )
  }
  func toList() -> [Any?] {
    return [
      gdprApplies,
      consentGiven,
      ccpaOptOut,
      coppa,
    ]
  }
  static func == (lhs: ConsentMessage, rhs: ConsentMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.gdprApplies, rhs.gdprApplies) && MessagesPigeonInternal.deepEquals(lhs.consentGiven, rhs.consentGiven) && MessagesPigeonInternal.deepEquals(lhs.ccpaOptOut, rhs.ccpaOptOut) && MessagesPigeonInternal.deepEquals(lhs.coppa, rhs.coppa)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConsentMessage")
    MessagesPigeonInternal.deepHash(value: gdprApplies, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: consentGiven, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ccpaOptOut, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: coppa, hasher: &hasher)
  }

  public var description: String {
    return "ConsentMessage(gdprApplies: \(String(describing: gdprApplies)), consentGiven: \(String(describing: consentGiven)), ccpaOptOut: \(String(describing: ccpaOptOut)), coppa: \(String(describing: coppa)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GatherRequest: Hashable, CustomStringConvertible {
  var forceForm: Bool
  var debugGeography: DebugGeographyMessage? = nil
  var testDeviceHashedIds: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GatherRequest? {
    let forceForm = pigeonVar_list[0] as! Bool
    let debugGeography: DebugGeographyMessage? = nilOrValue(pigeonVar_list[1])
    let testDeviceHashedIds = pigeonVar_list[2] as! [String]

    return GatherRequest(
      forceForm: forceForm,
      debugGeography: debugGeography,
      testDeviceHashedIds: testDeviceHashedIds
    )
  }
  func toList() -> [Any?] {
    return [
      forceForm,
      debugGeography,
      testDeviceHashedIds,
    ]
  }
  static func == (lhs: GatherRequest, rhs: GatherRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.forceForm, rhs.forceForm) && MessagesPigeonInternal.deepEquals(lhs.debugGeography, rhs.debugGeography) && MessagesPigeonInternal.deepEquals(lhs.testDeviceHashedIds, rhs.testDeviceHashedIds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GatherRequest")
    MessagesPigeonInternal.deepHash(value: forceForm, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: debugGeography, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: testDeviceHashedIds, hasher: &hasher)
  }

  public var description: String {
    return "GatherRequest(forceForm: \(String(describing: forceForm)), debugGeography: \(String(describing: debugGeography)), testDeviceHashedIds: \(String(describing: testDeviceHashedIds)))"
  }
}

/// UMP status plus the IAB values UMP stored on the device.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ConsentInfo: Hashable, CustomStringConvertible {
  var canRequestAds: Bool
  var privacyOptionsRequired: Bool
  /// `IABTCF_gdprApplies` (1 = applies, 0 = does not), if stored.
  var gdprApplies: Int64? = nil
  /// `IABTCF_TCString`.
  var tcString: String? = nil
  /// `IABTCF_PurposeConsents` ('0'/'1' per purpose).
  var purposeConsents: String? = nil
  /// `IABGPP_HDR_GppString`.
  var gppString: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConsentInfo? {
    let canRequestAds = pigeonVar_list[0] as! Bool
    let privacyOptionsRequired = pigeonVar_list[1] as! Bool
    let gdprApplies: Int64? = nilOrValue(pigeonVar_list[2])
    let tcString: String? = nilOrValue(pigeonVar_list[3])
    let purposeConsents: String? = nilOrValue(pigeonVar_list[4])
    let gppString: String? = nilOrValue(pigeonVar_list[5])

    return ConsentInfo(
      canRequestAds: canRequestAds,
      privacyOptionsRequired: privacyOptionsRequired,
      gdprApplies: gdprApplies,
      tcString: tcString,
      purposeConsents: purposeConsents,
      gppString: gppString
    )
  }
  func toList() -> [Any?] {
    return [
      canRequestAds,
      privacyOptionsRequired,
      gdprApplies,
      tcString,
      purposeConsents,
      gppString,
    ]
  }
  static func == (lhs: ConsentInfo, rhs: ConsentInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.canRequestAds, rhs.canRequestAds) && MessagesPigeonInternal.deepEquals(lhs.privacyOptionsRequired, rhs.privacyOptionsRequired) && MessagesPigeonInternal.deepEquals(lhs.gdprApplies, rhs.gdprApplies) && MessagesPigeonInternal.deepEquals(lhs.tcString, rhs.tcString) && MessagesPigeonInternal.deepEquals(lhs.purposeConsents, rhs.purposeConsents) && MessagesPigeonInternal.deepEquals(lhs.gppString, rhs.gppString)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConsentInfo")
    MessagesPigeonInternal.deepHash(value: canRequestAds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: privacyOptionsRequired, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: gdprApplies, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: tcString, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: purposeConsents, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: gppString, hasher: &hasher)
  }

  public var description: String {
    return "ConsentInfo(canRequestAds: \(String(describing: canRequestAds)), privacyOptionsRequired: \(String(describing: privacyOptionsRequired)), gdprApplies: \(String(describing: gdprApplies)), tcString: \(String(describing: tcString)), purposeConsents: \(String(describing: purposeConsents)), gppString: \(String(describing: gppString)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AdEventMessage: Hashable, CustomStringConvertible {
  var kind: AdEventKind
  var adId: String
  var format: AdFormatMessage
  /// An `AdErrorCode` name, for failure events.
  var errorCode: String? = nil
  var errorMessage: String? = nil
  var nativeCode: String? = nil
  var rewardAmount: Double? = nil
  var rewardType: String? = nil
  var width: Double? = nil
  var height: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AdEventMessage? {
    let kind = pigeonVar_list[0] as! AdEventKind
    let adId = pigeonVar_list[1] as! String
    let format = pigeonVar_list[2] as! AdFormatMessage
    let errorCode: String? = nilOrValue(pigeonVar_list[3])
    let errorMessage: String? = nilOrValue(pigeonVar_list[4])
    let nativeCode: String? = nilOrValue(pigeonVar_list[5])
    let rewardAmount: Double? = nilOrValue(pigeonVar_list[6])
    let rewardType: String? = nilOrValue(pigeonVar_list[7])
    let width: Double? = nilOrValue(pigeonVar_list[8])
    let height: Double? = nilOrValue(pigeonVar_list[9])

    return AdEventMessage(
      kind: kind,
      adId: adId,
      format: format,
      errorCode: errorCode,
      errorMessage: errorMessage,
      nativeCode: nativeCode,
      rewardAmount: rewardAmount,
      rewardType: rewardType,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      adId,
      format,
      errorCode,
      errorMessage,
      nativeCode,
      rewardAmount,
      rewardType,
      width,
      height,
    ]
  }
  static func == (lhs: AdEventMessage, rhs: AdEventMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.adId, rhs.adId) && MessagesPigeonInternal.deepEquals(lhs.format, rhs.format) && MessagesPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && MessagesPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage) && MessagesPigeonInternal.deepEquals(lhs.nativeCode, rhs.nativeCode) && MessagesPigeonInternal.deepEquals(lhs.rewardAmount, rhs.rewardAmount) && MessagesPigeonInternal.deepEquals(lhs.rewardType, rhs.rewardType) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AdEventMessage")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: adId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nativeCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rewardAmount, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rewardType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "AdEventMessage(kind: \(String(describing: kind)), adId: \(String(describing: adId)), format: \(String(describing: format)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)), nativeCode: \(String(describing: nativeCode)), rewardAmount: \(String(describing: rewardAmount)), rewardType: \(String(describing: rewardType)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AdFormatMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AdEventKind(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DebugGeographyMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return InitRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return InitInfo.fromList(self.readValue() as! [Any?])
    case 134:
      return ConsentMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return GatherRequest.fromList(self.readValue() as! [Any?])
    case 136:
      return ConsentInfo.fromList(self.readValue() as! [Any?])
    case 137:
      return AdEventMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AdFormatMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AdEventKind {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? DebugGeographyMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? InitRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? InitInfo {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ConsentMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? GatherRequest {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ConsentInfo {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? AdEventMessage {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Dart → native. Failures are reported as platform errors whose `code` is an
/// `AdErrorCode` name and whose `details` is the SDK's own error code.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AdmobHostApi {
  func initialize(request: InitRequest) async throws -> InitInfo
  /// Loads a full-screen ad and returns its id.
  func load(format: AdFormatMessage, adUnitId: String) async throws -> String
  /// Completes when the ad is presented (or failed to present).
  func show(adId: String) async throws
  func destroy(adId: String) throws
  func applyConsent(consent: ConsentMessage) throws
  func dispose() throws
  func gatherConsent(request: GatherRequest) async throws -> ConsentInfo
  func showPrivacyOptions() async throws
  func consentInfo() throws -> ConsentInfo
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AdmobHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AdmobHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AdmobHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.unified_ads_admob.AdmobHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! InitRequest
        Task { @MainActor in
          do {
            let result = try await api.initialize(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Loads a full-screen ad and returns its id.
    let loadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.unified_ads_admob.AdmobHostApi.load\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let formatArg = args[0] as! AdFormatMessage
        let adUnitIdArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.load(format: formatArg, adUnitId: adUnitIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadChannel.setMessageHandler(nil)
    }
    /// Completes when the ad is presented (or failed to present).
    let showChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.unified_ads_admob.AdmobHostApi.show\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.show(adId: adIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      showChannel.setMessageHandler(nil)
    }
    let destroyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.unified_ads_admob.AdmobHostApi.destroy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! String
        do {
          try api.destroy(adId: adIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      destroyChannel.setMessageHandler(nil)
    }
    let applyConsentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.unified_ads_admob.AdmobHostApi.applyConsent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyConsentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let consentArg = args[0] as! ConsentMessage
        do {
          try api.applyConsent(consent: consentArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      applyConsentChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.unified_ads_admob.AdmobHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let gatherConsentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.unified_ads_admob.AdmobHostApi.gatherConsent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      gatherConsentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! GatherRequest
        Task { @MainActor in
          do {
            let result = try await api.gatherConsent(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      gatherConsentChannel.setMessageHandler(nil)
    }
    let showPrivacyOptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.unified_ads_admob.AdmobHostApi.showPrivacyOptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showPrivacyOptionsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.showPrivacyOptions()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      showPrivacyOptionsChannel.setMessageHandler(nil)
    }
    let consentInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.unified_ads_admob.AdmobHostApi.consentInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      consentInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.consentInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      consentInfoChannel.setMessageHandler(nil)
    }
  }
}

/// Native → Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AdmobEventsApiProtocol {
  @MainActor func onAdEvent(event eventArg: AdEventMessage) async throws
}
class AdmobEventsApi: AdmobEventsApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  @MainActor func onAdEvent(event eventArg: AdEventMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.unified_ads_admob.AdmobEventsApi.onAdEvent\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
